// Code generated by protoc-gen-go. DO NOT EDIT.
// source: status-service.proto

package protobuffer_def // import "."

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CMD int32

const (
	CMD_REGISTER_STATUS          CMD = 0
	CMD_QUERY_STATUS             CMD = 1
	CMD_CREATE_CHAT_ROOM         CMD = 2
	CMD_UPDATE_OFF_LINE          CMD = 3
	CMD_DEL_CHAT_ROOM            CMD = 4
	CMD_SINGLE_CALL_NOTIFY       CMD = 5
	CMD_FORCE_TERMINAL_NOTIFY    CMD = 6
	CMD_SINGLE_ANSWER_SIG_TO_SIG CMD = 7
	CMD_GET_CHAT_ROOM_REQ        CMD = 8
	CMD_SINGLE_REFUSE_SIG_TO_SIG CMD = 9
	CMD_HANG_UP_SIG_TO_SIG       CMD = 10
	CMD_TERMINAL_SIG_TO_SIG      CMD = 11
	CMD_OFFER_CALL_SIG_TO_SIG    CMD = 12
	CMD_OFFER_ANSWER_SIG_TO_SIG  CMD = 13
	CMD_ICE_CALL_SIG_TO_SIG      CMD = 14
	CMD_ICE_ANSWER_SIG_TO_SIG    CMD = 15
	CMD_CMD_MEDIA_TO_AUDIO       CMD = 16
	CMD_CMD_KICK_USER            CMD = 17
	CMD_UPDATE_ON_LINE           CMD = 18
)

var CMD_name = map[int32]string{
	0:  "REGISTER_STATUS",
	1:  "QUERY_STATUS",
	2:  "CREATE_CHAT_ROOM",
	3:  "UPDATE_OFF_LINE",
	4:  "DEL_CHAT_ROOM",
	5:  "SINGLE_CALL_NOTIFY",
	6:  "FORCE_TERMINAL_NOTIFY",
	7:  "SINGLE_ANSWER_SIG_TO_SIG",
	8:  "GET_CHAT_ROOM_REQ",
	9:  "SINGLE_REFUSE_SIG_TO_SIG",
	10: "HANG_UP_SIG_TO_SIG",
	11: "TERMINAL_SIG_TO_SIG",
	12: "OFFER_CALL_SIG_TO_SIG",
	13: "OFFER_ANSWER_SIG_TO_SIG",
	14: "ICE_CALL_SIG_TO_SIG",
	15: "ICE_ANSWER_SIG_TO_SIG",
	16: "CMD_MEDIA_TO_AUDIO",
	17: "CMD_KICK_USER",
	18: "UPDATE_ON_LINE",
}
var CMD_value = map[string]int32{
	"REGISTER_STATUS":          0,
	"QUERY_STATUS":             1,
	"CREATE_CHAT_ROOM":         2,
	"UPDATE_OFF_LINE":          3,
	"DEL_CHAT_ROOM":            4,
	"SINGLE_CALL_NOTIFY":       5,
	"FORCE_TERMINAL_NOTIFY":    6,
	"SINGLE_ANSWER_SIG_TO_SIG": 7,
	"GET_CHAT_ROOM_REQ":        8,
	"SINGLE_REFUSE_SIG_TO_SIG": 9,
	"HANG_UP_SIG_TO_SIG":       10,
	"TERMINAL_SIG_TO_SIG":      11,
	"OFFER_CALL_SIG_TO_SIG":    12,
	"OFFER_ANSWER_SIG_TO_SIG":  13,
	"ICE_CALL_SIG_TO_SIG":      14,
	"ICE_ANSWER_SIG_TO_SIG":    15,
	"CMD_MEDIA_TO_AUDIO":       16,
	"CMD_KICK_USER":            17,
	"UPDATE_ON_LINE":           18,
}

func (x CMD) String() string {
	return proto.EnumName(CMD_name, int32(x))
}
func (CMD) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{0}
}

type ReturnCode int32

const (
	ReturnCode_SUCCESS               ReturnCode = 0
	ReturnCode_UNKOWN_CMD            ReturnCode = 1
	ReturnCode_BODY_IS_NULL          ReturnCode = 2
	ReturnCode_DESERIALIZATION_ERROR ReturnCode = 3
	ReturnCode_SERIALIZATION_ERROR   ReturnCode = 4
	ReturnCode_UNKOWN_ERROR          ReturnCode = 5
)

var ReturnCode_name = map[int32]string{
	0: "SUCCESS",
	1: "UNKOWN_CMD",
	2: "BODY_IS_NULL",
	3: "DESERIALIZATION_ERROR",
	4: "SERIALIZATION_ERROR",
	5: "UNKOWN_ERROR",
}
var ReturnCode_value = map[string]int32{
	"SUCCESS":               0,
	"UNKOWN_CMD":            1,
	"BODY_IS_NULL":          2,
	"DESERIALIZATION_ERROR": 3,
	"SERIALIZATION_ERROR":   4,
	"UNKOWN_ERROR":          5,
}

func (x ReturnCode) String() string {
	return proto.EnumName(ReturnCode_name, int32(x))
}
func (ReturnCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{1}
}

type BaseRequest struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	C                    CMD      `protobuf:"varint,2,opt,name=c,proto3,enum=CMD" json:"c,omitempty"`
	Body                 *any.Any `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseRequest) Reset()         { *m = BaseRequest{} }
func (m *BaseRequest) String() string { return proto.CompactTextString(m) }
func (*BaseRequest) ProtoMessage()    {}
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{0}
}
func (m *BaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseRequest.Unmarshal(m, b)
}
func (m *BaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseRequest.Marshal(b, m, deterministic)
}
func (dst *BaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseRequest.Merge(dst, src)
}
func (m *BaseRequest) XXX_Size() int {
	return xxx_messageInfo_BaseRequest.Size(m)
}
func (m *BaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BaseRequest proto.InternalMessageInfo

func (m *BaseRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *BaseRequest) GetC() CMD {
	if m != nil {
		return m.C
	}
	return CMD_REGISTER_STATUS
}

func (m *BaseRequest) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

type BaseResponse struct {
	RequestId            string     `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Code                 ReturnCode `protobuf:"varint,2,opt,name=code,proto3,enum=ReturnCode" json:"code,omitempty"`
	Desc                 string     `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	C                    CMD        `protobuf:"varint,4,opt,name=c,proto3,enum=CMD" json:"c,omitempty"`
	Body                 *any.Any   `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BaseResponse) Reset()         { *m = BaseResponse{} }
func (m *BaseResponse) String() string { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()    {}
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{1}
}
func (m *BaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResponse.Unmarshal(m, b)
}
func (m *BaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResponse.Marshal(b, m, deterministic)
}
func (dst *BaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResponse.Merge(dst, src)
}
func (m *BaseResponse) XXX_Size() int {
	return xxx_messageInfo_BaseResponse.Size(m)
}
func (m *BaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResponse proto.InternalMessageInfo

func (m *BaseResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *BaseResponse) GetCode() ReturnCode {
	if m != nil {
		return m.Code
	}
	return ReturnCode_SUCCESS
}

func (m *BaseResponse) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *BaseResponse) GetC() CMD {
	if m != nil {
		return m.C
	}
	return CMD_REGISTER_STATUS
}

func (m *BaseResponse) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

// 注册状态       请求
type RegisterStatusRequest struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	RoomList             []string `protobuf:"bytes,2,rep,name=room_list,json=roomList,proto3" json:"room_list,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserAvator           string   `protobuf:"bytes,5,opt,name=user_avator,json=userAvator,proto3" json:"user_avator,omitempty"`
	RegisterInfo         string   `protobuf:"bytes,6,opt,name=register_info,json=registerInfo,proto3" json:"register_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterStatusRequest) Reset()         { *m = RegisterStatusRequest{} }
func (m *RegisterStatusRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterStatusRequest) ProtoMessage()    {}
func (*RegisterStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{2}
}
func (m *RegisterStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterStatusRequest.Unmarshal(m, b)
}
func (m *RegisterStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterStatusRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterStatusRequest.Merge(dst, src)
}
func (m *RegisterStatusRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterStatusRequest.Size(m)
}
func (m *RegisterStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterStatusRequest proto.InternalMessageInfo

func (m *RegisterStatusRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *RegisterStatusRequest) GetRoomList() []string {
	if m != nil {
		return m.RoomList
	}
	return nil
}

func (m *RegisterStatusRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterStatusRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegisterStatusRequest) GetUserAvator() string {
	if m != nil {
		return m.UserAvator
	}
	return ""
}

func (m *RegisterStatusRequest) GetRegisterInfo() string {
	if m != nil {
		return m.RegisterInfo
	}
	return ""
}

// 注册状态        响应
type RegisterStatusResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterStatusResponse) Reset()         { *m = RegisterStatusResponse{} }
func (m *RegisterStatusResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterStatusResponse) ProtoMessage()    {}
func (*RegisterStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{3}
}
func (m *RegisterStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterStatusResponse.Unmarshal(m, b)
}
func (m *RegisterStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterStatusResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterStatusResponse.Merge(dst, src)
}
func (m *RegisterStatusResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterStatusResponse.Size(m)
}
func (m *RegisterStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterStatusResponse proto.InternalMessageInfo

// 查询设备状态    请求
type QueryStatusRequest struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryStatusRequest) Reset()         { *m = QueryStatusRequest{} }
func (m *QueryStatusRequest) String() string { return proto.CompactTextString(m) }
func (*QueryStatusRequest) ProtoMessage()    {}
func (*QueryStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{4}
}
func (m *QueryStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryStatusRequest.Unmarshal(m, b)
}
func (m *QueryStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryStatusRequest.Marshal(b, m, deterministic)
}
func (dst *QueryStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStatusRequest.Merge(dst, src)
}
func (m *QueryStatusRequest) XXX_Size() int {
	return xxx_messageInfo_QueryStatusRequest.Size(m)
}
func (m *QueryStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStatusRequest proto.InternalMessageInfo

func (m *QueryStatusRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

// 查询设备状态    响应
type QueryStatusResponse struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	RoomList             []string `protobuf:"bytes,2,rep,name=room_list,json=roomList,proto3" json:"room_list,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserAvator           string   `protobuf:"bytes,5,opt,name=user_avator,json=userAvator,proto3" json:"user_avator,omitempty"`
	State                int32    `protobuf:"varint,6,opt,name=state,proto3" json:"state,omitempty"`
	ChatRoomId           string   `protobuf:"bytes,7,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	LastChat             int64    `protobuf:"varint,8,opt,name=last_chat,json=lastChat,proto3" json:"last_chat,omitempty"`
	RegAddr              string   `protobuf:"bytes,9,opt,name=reg_addr,json=regAddr,proto3" json:"reg_addr,omitempty"`
	OffLine              bool     `protobuf:"varint,10,opt,name=off_line,json=offLine,proto3" json:"off_line,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryStatusResponse) Reset()         { *m = QueryStatusResponse{} }
func (m *QueryStatusResponse) String() string { return proto.CompactTextString(m) }
func (*QueryStatusResponse) ProtoMessage()    {}
func (*QueryStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{5}
}
func (m *QueryStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryStatusResponse.Unmarshal(m, b)
}
func (m *QueryStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryStatusResponse.Marshal(b, m, deterministic)
}
func (dst *QueryStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStatusResponse.Merge(dst, src)
}
func (m *QueryStatusResponse) XXX_Size() int {
	return xxx_messageInfo_QueryStatusResponse.Size(m)
}
func (m *QueryStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStatusResponse proto.InternalMessageInfo

func (m *QueryStatusResponse) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *QueryStatusResponse) GetRoomList() []string {
	if m != nil {
		return m.RoomList
	}
	return nil
}

func (m *QueryStatusResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *QueryStatusResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *QueryStatusResponse) GetUserAvator() string {
	if m != nil {
		return m.UserAvator
	}
	return ""
}

func (m *QueryStatusResponse) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *QueryStatusResponse) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *QueryStatusResponse) GetLastChat() int64 {
	if m != nil {
		return m.LastChat
	}
	return 0
}

func (m *QueryStatusResponse) GetRegAddr() string {
	if m != nil {
		return m.RegAddr
	}
	return ""
}

func (m *QueryStatusResponse) GetOffLine() bool {
	if m != nil {
		return m.OffLine
	}
	return false
}

// 创建聊天室 请求
type CreateChatRoomReq struct {
	Caller               string   `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	Answer               string   `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateChatRoomReq) Reset()         { *m = CreateChatRoomReq{} }
func (m *CreateChatRoomReq) String() string { return proto.CompactTextString(m) }
func (*CreateChatRoomReq) ProtoMessage()    {}
func (*CreateChatRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{6}
}
func (m *CreateChatRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateChatRoomReq.Unmarshal(m, b)
}
func (m *CreateChatRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateChatRoomReq.Marshal(b, m, deterministic)
}
func (dst *CreateChatRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateChatRoomReq.Merge(dst, src)
}
func (m *CreateChatRoomReq) XXX_Size() int {
	return xxx_messageInfo_CreateChatRoomReq.Size(m)
}
func (m *CreateChatRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateChatRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateChatRoomReq proto.InternalMessageInfo

func (m *CreateChatRoomReq) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *CreateChatRoomReq) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

// 创建聊天室 响应
type CreateChatRoomRsp struct {
	Caller               string   `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	Answer               string   `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	ChatRoomId           string   `protobuf:"bytes,3,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateChatRoomRsp) Reset()         { *m = CreateChatRoomRsp{} }
func (m *CreateChatRoomRsp) String() string { return proto.CompactTextString(m) }
func (*CreateChatRoomRsp) ProtoMessage()    {}
func (*CreateChatRoomRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{7}
}
func (m *CreateChatRoomRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateChatRoomRsp.Unmarshal(m, b)
}
func (m *CreateChatRoomRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateChatRoomRsp.Marshal(b, m, deterministic)
}
func (dst *CreateChatRoomRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateChatRoomRsp.Merge(dst, src)
}
func (m *CreateChatRoomRsp) XXX_Size() int {
	return xxx_messageInfo_CreateChatRoomRsp.Size(m)
}
func (m *CreateChatRoomRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateChatRoomRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateChatRoomRsp proto.InternalMessageInfo

func (m *CreateChatRoomRsp) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *CreateChatRoomRsp) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

func (m *CreateChatRoomRsp) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

// 更新离线状态 请求
type UpdateOfflineReq struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOfflineReq) Reset()         { *m = UpdateOfflineReq{} }
func (m *UpdateOfflineReq) String() string { return proto.CompactTextString(m) }
func (*UpdateOfflineReq) ProtoMessage()    {}
func (*UpdateOfflineReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{8}
}
func (m *UpdateOfflineReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOfflineReq.Unmarshal(m, b)
}
func (m *UpdateOfflineReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOfflineReq.Marshal(b, m, deterministic)
}
func (dst *UpdateOfflineReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOfflineReq.Merge(dst, src)
}
func (m *UpdateOfflineReq) XXX_Size() int {
	return xxx_messageInfo_UpdateOfflineReq.Size(m)
}
func (m *UpdateOfflineReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOfflineReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOfflineReq proto.InternalMessageInfo

func (m *UpdateOfflineReq) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

// 更新离线状态 响应
type UpdateOfflineRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOfflineRsp) Reset()         { *m = UpdateOfflineRsp{} }
func (m *UpdateOfflineRsp) String() string { return proto.CompactTextString(m) }
func (*UpdateOfflineRsp) ProtoMessage()    {}
func (*UpdateOfflineRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{9}
}
func (m *UpdateOfflineRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOfflineRsp.Unmarshal(m, b)
}
func (m *UpdateOfflineRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOfflineRsp.Marshal(b, m, deterministic)
}
func (dst *UpdateOfflineRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOfflineRsp.Merge(dst, src)
}
func (m *UpdateOfflineRsp) XXX_Size() int {
	return xxx_messageInfo_UpdateOfflineRsp.Size(m)
}
func (m *UpdateOfflineRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOfflineRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOfflineRsp proto.InternalMessageInfo

// 删除聊天室 请求
type DelChatRoomReq struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelChatRoomReq) Reset()         { *m = DelChatRoomReq{} }
func (m *DelChatRoomReq) String() string { return proto.CompactTextString(m) }
func (*DelChatRoomReq) ProtoMessage()    {}
func (*DelChatRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{10}
}
func (m *DelChatRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelChatRoomReq.Unmarshal(m, b)
}
func (m *DelChatRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelChatRoomReq.Marshal(b, m, deterministic)
}
func (dst *DelChatRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelChatRoomReq.Merge(dst, src)
}
func (m *DelChatRoomReq) XXX_Size() int {
	return xxx_messageInfo_DelChatRoomReq.Size(m)
}
func (m *DelChatRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelChatRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelChatRoomReq proto.InternalMessageInfo

func (m *DelChatRoomReq) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

// 删除聊天室 响应
type DelChatRoomRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelChatRoomRsp) Reset()         { *m = DelChatRoomRsp{} }
func (m *DelChatRoomRsp) String() string { return proto.CompactTextString(m) }
func (*DelChatRoomRsp) ProtoMessage()    {}
func (*DelChatRoomRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{11}
}
func (m *DelChatRoomRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelChatRoomRsp.Unmarshal(m, b)
}
func (m *DelChatRoomRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelChatRoomRsp.Marshal(b, m, deterministic)
}
func (dst *DelChatRoomRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelChatRoomRsp.Merge(dst, src)
}
func (m *DelChatRoomRsp) XXX_Size() int {
	return xxx_messageInfo_DelChatRoomRsp.Size(m)
}
func (m *DelChatRoomRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelChatRoomRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DelChatRoomRsp proto.InternalMessageInfo

// 强制中断通话请求
type ForceTerminateNotify struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	OtherId              string   `protobuf:"bytes,2,opt,name=other_id,json=otherId,proto3" json:"other_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForceTerminateNotify) Reset()         { *m = ForceTerminateNotify{} }
func (m *ForceTerminateNotify) String() string { return proto.CompactTextString(m) }
func (*ForceTerminateNotify) ProtoMessage()    {}
func (*ForceTerminateNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{12}
}
func (m *ForceTerminateNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForceTerminateNotify.Unmarshal(m, b)
}
func (m *ForceTerminateNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForceTerminateNotify.Marshal(b, m, deterministic)
}
func (dst *ForceTerminateNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForceTerminateNotify.Merge(dst, src)
}
func (m *ForceTerminateNotify) XXX_Size() int {
	return xxx_messageInfo_ForceTerminateNotify.Size(m)
}
func (m *ForceTerminateNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_ForceTerminateNotify.DiscardUnknown(m)
}

var xxx_messageInfo_ForceTerminateNotify proto.InternalMessageInfo

func (m *ForceTerminateNotify) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *ForceTerminateNotify) GetOtherId() string {
	if m != nil {
		return m.OtherId
	}
	return ""
}

// answer的sig服务器将应答结果通知主叫方sig服务器
type SingleAnswerSigToSig struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	DeviceModel          string   `protobuf:"bytes,2,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	CallerId             string   `protobuf:"bytes,3,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	AnswerId             string   `protobuf:"bytes,4,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleAnswerSigToSig) Reset()         { *m = SingleAnswerSigToSig{} }
func (m *SingleAnswerSigToSig) String() string { return proto.CompactTextString(m) }
func (*SingleAnswerSigToSig) ProtoMessage()    {}
func (*SingleAnswerSigToSig) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{13}
}
func (m *SingleAnswerSigToSig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleAnswerSigToSig.Unmarshal(m, b)
}
func (m *SingleAnswerSigToSig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleAnswerSigToSig.Marshal(b, m, deterministic)
}
func (dst *SingleAnswerSigToSig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleAnswerSigToSig.Merge(dst, src)
}
func (m *SingleAnswerSigToSig) XXX_Size() int {
	return xxx_messageInfo_SingleAnswerSigToSig.Size(m)
}
func (m *SingleAnswerSigToSig) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleAnswerSigToSig.DiscardUnknown(m)
}

var xxx_messageInfo_SingleAnswerSigToSig proto.InternalMessageInfo

func (m *SingleAnswerSigToSig) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *SingleAnswerSigToSig) GetDeviceModel() string {
	if m != nil {
		return m.DeviceModel
	}
	return ""
}

func (m *SingleAnswerSigToSig) GetCallerId() string {
	if m != nil {
		return m.CallerId
	}
	return ""
}

func (m *SingleAnswerSigToSig) GetAnswerId() string {
	if m != nil {
		return m.AnswerId
	}
	return ""
}

// 获取聊天室信息 请求
type GetChatRoomReq struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChatRoomReq) Reset()         { *m = GetChatRoomReq{} }
func (m *GetChatRoomReq) String() string { return proto.CompactTextString(m) }
func (*GetChatRoomReq) ProtoMessage()    {}
func (*GetChatRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{14}
}
func (m *GetChatRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChatRoomReq.Unmarshal(m, b)
}
func (m *GetChatRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChatRoomReq.Marshal(b, m, deterministic)
}
func (dst *GetChatRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChatRoomReq.Merge(dst, src)
}
func (m *GetChatRoomReq) XXX_Size() int {
	return xxx_messageInfo_GetChatRoomReq.Size(m)
}
func (m *GetChatRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChatRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetChatRoomReq proto.InternalMessageInfo

func (m *GetChatRoomReq) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

// 获取聊天室信息 响应
type GetChatRoomRsp struct {
	Caller               string   `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	Answer               string   `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	ChatRoomId           string   `protobuf:"bytes,3,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChatRoomRsp) Reset()         { *m = GetChatRoomRsp{} }
func (m *GetChatRoomRsp) String() string { return proto.CompactTextString(m) }
func (*GetChatRoomRsp) ProtoMessage()    {}
func (*GetChatRoomRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{15}
}
func (m *GetChatRoomRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChatRoomRsp.Unmarshal(m, b)
}
func (m *GetChatRoomRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChatRoomRsp.Marshal(b, m, deterministic)
}
func (dst *GetChatRoomRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChatRoomRsp.Merge(dst, src)
}
func (m *GetChatRoomRsp) XXX_Size() int {
	return xxx_messageInfo_GetChatRoomRsp.Size(m)
}
func (m *GetChatRoomRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChatRoomRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetChatRoomRsp proto.InternalMessageInfo

func (m *GetChatRoomRsp) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *GetChatRoomRsp) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

func (m *GetChatRoomRsp) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

// 被叫方的sig服务器拒绝接听，发送给主叫方sig服务器
type SingleRefuseSigToSig struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	CallerId             string   `protobuf:"bytes,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	AnswerId             string   `protobuf:"bytes,3,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleRefuseSigToSig) Reset()         { *m = SingleRefuseSigToSig{} }
func (m *SingleRefuseSigToSig) String() string { return proto.CompactTextString(m) }
func (*SingleRefuseSigToSig) ProtoMessage()    {}
func (*SingleRefuseSigToSig) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{16}
}
func (m *SingleRefuseSigToSig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleRefuseSigToSig.Unmarshal(m, b)
}
func (m *SingleRefuseSigToSig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleRefuseSigToSig.Marshal(b, m, deterministic)
}
func (dst *SingleRefuseSigToSig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleRefuseSigToSig.Merge(dst, src)
}
func (m *SingleRefuseSigToSig) XXX_Size() int {
	return xxx_messageInfo_SingleRefuseSigToSig.Size(m)
}
func (m *SingleRefuseSigToSig) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleRefuseSigToSig.DiscardUnknown(m)
}

var xxx_messageInfo_SingleRefuseSigToSig proto.InternalMessageInfo

func (m *SingleRefuseSigToSig) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *SingleRefuseSigToSig) GetCallerId() string {
	if m != nil {
		return m.CallerId
	}
	return ""
}

func (m *SingleRefuseSigToSig) GetAnswerId() string {
	if m != nil {
		return m.AnswerId
	}
	return ""
}

// 主叫方挂断，主叫方服务器发送给被叫方服务器
type HangUpSigToSig struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	AnswerId             string   `protobuf:"bytes,2,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HangUpSigToSig) Reset()         { *m = HangUpSigToSig{} }
func (m *HangUpSigToSig) String() string { return proto.CompactTextString(m) }
func (*HangUpSigToSig) ProtoMessage()    {}
func (*HangUpSigToSig) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{17}
}
func (m *HangUpSigToSig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HangUpSigToSig.Unmarshal(m, b)
}
func (m *HangUpSigToSig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HangUpSigToSig.Marshal(b, m, deterministic)
}
func (dst *HangUpSigToSig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HangUpSigToSig.Merge(dst, src)
}
func (m *HangUpSigToSig) XXX_Size() int {
	return xxx_messageInfo_HangUpSigToSig.Size(m)
}
func (m *HangUpSigToSig) XXX_DiscardUnknown() {
	xxx_messageInfo_HangUpSigToSig.DiscardUnknown(m)
}

var xxx_messageInfo_HangUpSigToSig proto.InternalMessageInfo

func (m *HangUpSigToSig) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *HangUpSigToSig) GetAnswerId() string {
	if m != nil {
		return m.AnswerId
	}
	return ""
}

// 任一方挂断，挂断方的服务器通知另一方
type SingleTerminal struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	CancelId             string   `protobuf:"bytes,2,opt,name=cancel_id,json=cancelId,proto3" json:"cancel_id,omitempty"`
	BeCanceledId         string   `protobuf:"bytes,3,opt,name=be_canceled_id,json=beCanceledId,proto3" json:"be_canceled_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleTerminal) Reset()         { *m = SingleTerminal{} }
func (m *SingleTerminal) String() string { return proto.CompactTextString(m) }
func (*SingleTerminal) ProtoMessage()    {}
func (*SingleTerminal) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{18}
}
func (m *SingleTerminal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleTerminal.Unmarshal(m, b)
}
func (m *SingleTerminal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleTerminal.Marshal(b, m, deterministic)
}
func (dst *SingleTerminal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleTerminal.Merge(dst, src)
}
func (m *SingleTerminal) XXX_Size() int {
	return xxx_messageInfo_SingleTerminal.Size(m)
}
func (m *SingleTerminal) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleTerminal.DiscardUnknown(m)
}

var xxx_messageInfo_SingleTerminal proto.InternalMessageInfo

func (m *SingleTerminal) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *SingleTerminal) GetCancelId() string {
	if m != nil {
		return m.CancelId
	}
	return ""
}

func (m *SingleTerminal) GetBeCanceledId() string {
	if m != nil {
		return m.BeCanceledId
	}
	return ""
}

// 主叫方发送offer
type OfferCall struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	CallerId             string   `protobuf:"bytes,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	AnswerId             string   `protobuf:"bytes,3,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"`
	Sdp                  string   `protobuf:"bytes,4,opt,name=sdp,proto3" json:"sdp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfferCall) Reset()         { *m = OfferCall{} }
func (m *OfferCall) String() string { return proto.CompactTextString(m) }
func (*OfferCall) ProtoMessage()    {}
func (*OfferCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{19}
}
func (m *OfferCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferCall.Unmarshal(m, b)
}
func (m *OfferCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferCall.Marshal(b, m, deterministic)
}
func (dst *OfferCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferCall.Merge(dst, src)
}
func (m *OfferCall) XXX_Size() int {
	return xxx_messageInfo_OfferCall.Size(m)
}
func (m *OfferCall) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferCall.DiscardUnknown(m)
}

var xxx_messageInfo_OfferCall proto.InternalMessageInfo

func (m *OfferCall) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *OfferCall) GetCallerId() string {
	if m != nil {
		return m.CallerId
	}
	return ""
}

func (m *OfferCall) GetAnswerId() string {
	if m != nil {
		return m.AnswerId
	}
	return ""
}

func (m *OfferCall) GetSdp() string {
	if m != nil {
		return m.Sdp
	}
	return ""
}

// 被叫方发送offer
type OfferAnswer struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	CallerId             string   `protobuf:"bytes,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	AnswerId             string   `protobuf:"bytes,3,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"`
	Sdp                  string   `protobuf:"bytes,4,opt,name=sdp,proto3" json:"sdp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfferAnswer) Reset()         { *m = OfferAnswer{} }
func (m *OfferAnswer) String() string { return proto.CompactTextString(m) }
func (*OfferAnswer) ProtoMessage()    {}
func (*OfferAnswer) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{20}
}
func (m *OfferAnswer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferAnswer.Unmarshal(m, b)
}
func (m *OfferAnswer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferAnswer.Marshal(b, m, deterministic)
}
func (dst *OfferAnswer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferAnswer.Merge(dst, src)
}
func (m *OfferAnswer) XXX_Size() int {
	return xxx_messageInfo_OfferAnswer.Size(m)
}
func (m *OfferAnswer) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferAnswer.DiscardUnknown(m)
}

var xxx_messageInfo_OfferAnswer proto.InternalMessageInfo

func (m *OfferAnswer) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *OfferAnswer) GetCallerId() string {
	if m != nil {
		return m.CallerId
	}
	return ""
}

func (m *OfferAnswer) GetAnswerId() string {
	if m != nil {
		return m.AnswerId
	}
	return ""
}

func (m *OfferAnswer) GetSdp() string {
	if m != nil {
		return m.Sdp
	}
	return ""
}

// 主叫方发送ice
type IceCall struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	CallerId             string   `protobuf:"bytes,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	AnswerId             string   `protobuf:"bytes,3,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"`
	IceCandidate         string   `protobuf:"bytes,4,opt,name=ice_candidate,json=iceCandidate,proto3" json:"ice_candidate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IceCall) Reset()         { *m = IceCall{} }
func (m *IceCall) String() string { return proto.CompactTextString(m) }
func (*IceCall) ProtoMessage()    {}
func (*IceCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{21}
}
func (m *IceCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IceCall.Unmarshal(m, b)
}
func (m *IceCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IceCall.Marshal(b, m, deterministic)
}
func (dst *IceCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IceCall.Merge(dst, src)
}
func (m *IceCall) XXX_Size() int {
	return xxx_messageInfo_IceCall.Size(m)
}
func (m *IceCall) XXX_DiscardUnknown() {
	xxx_messageInfo_IceCall.DiscardUnknown(m)
}

var xxx_messageInfo_IceCall proto.InternalMessageInfo

func (m *IceCall) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *IceCall) GetCallerId() string {
	if m != nil {
		return m.CallerId
	}
	return ""
}

func (m *IceCall) GetAnswerId() string {
	if m != nil {
		return m.AnswerId
	}
	return ""
}

func (m *IceCall) GetIceCandidate() string {
	if m != nil {
		return m.IceCandidate
	}
	return ""
}

// 被叫方发送ice
type IceAnswer struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	CallerId             string   `protobuf:"bytes,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	AnswerId             string   `protobuf:"bytes,3,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"`
	IceCandidate         string   `protobuf:"bytes,4,opt,name=ice_candidate,json=iceCandidate,proto3" json:"ice_candidate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IceAnswer) Reset()         { *m = IceAnswer{} }
func (m *IceAnswer) String() string { return proto.CompactTextString(m) }
func (*IceAnswer) ProtoMessage()    {}
func (*IceAnswer) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{22}
}
func (m *IceAnswer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IceAnswer.Unmarshal(m, b)
}
func (m *IceAnswer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IceAnswer.Marshal(b, m, deterministic)
}
func (dst *IceAnswer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IceAnswer.Merge(dst, src)
}
func (m *IceAnswer) XXX_Size() int {
	return xxx_messageInfo_IceAnswer.Size(m)
}
func (m *IceAnswer) XXX_DiscardUnknown() {
	xxx_messageInfo_IceAnswer.DiscardUnknown(m)
}

var xxx_messageInfo_IceAnswer proto.InternalMessageInfo

func (m *IceAnswer) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *IceAnswer) GetCallerId() string {
	if m != nil {
		return m.CallerId
	}
	return ""
}

func (m *IceAnswer) GetAnswerId() string {
	if m != nil {
		return m.AnswerId
	}
	return ""
}

func (m *IceAnswer) GetIceCandidate() string {
	if m != nil {
		return m.IceCandidate
	}
	return ""
}

// 媒体转化为音频
type MediaToAudio struct {
	ChatRoomId           string   `protobuf:"bytes,1,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	ConvertId            string   `protobuf:"bytes,2,opt,name=convert_id,json=convertId,proto3" json:"convert_id,omitempty"`
	BeConvertId          string   `protobuf:"bytes,3,opt,name=be_convert_id,json=beConvertId,proto3" json:"be_convert_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MediaToAudio) Reset()         { *m = MediaToAudio{} }
func (m *MediaToAudio) String() string { return proto.CompactTextString(m) }
func (*MediaToAudio) ProtoMessage()    {}
func (*MediaToAudio) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{23}
}
func (m *MediaToAudio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MediaToAudio.Unmarshal(m, b)
}
func (m *MediaToAudio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MediaToAudio.Marshal(b, m, deterministic)
}
func (dst *MediaToAudio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MediaToAudio.Merge(dst, src)
}
func (m *MediaToAudio) XXX_Size() int {
	return xxx_messageInfo_MediaToAudio.Size(m)
}
func (m *MediaToAudio) XXX_DiscardUnknown() {
	xxx_messageInfo_MediaToAudio.DiscardUnknown(m)
}

var xxx_messageInfo_MediaToAudio proto.InternalMessageInfo

func (m *MediaToAudio) GetChatRoomId() string {
	if m != nil {
		return m.ChatRoomId
	}
	return ""
}

func (m *MediaToAudio) GetConvertId() string {
	if m != nil {
		return m.ConvertId
	}
	return ""
}

func (m *MediaToAudio) GetBeConvertId() string {
	if m != nil {
		return m.BeConvertId
	}
	return ""
}

// 踢人通知
type KickPerson struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickPerson) Reset()         { *m = KickPerson{} }
func (m *KickPerson) String() string { return proto.CompactTextString(m) }
func (*KickPerson) ProtoMessage()    {}
func (*KickPerson) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{24}
}
func (m *KickPerson) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickPerson.Unmarshal(m, b)
}
func (m *KickPerson) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickPerson.Marshal(b, m, deterministic)
}
func (dst *KickPerson) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickPerson.Merge(dst, src)
}
func (m *KickPerson) XXX_Size() int {
	return xxx_messageInfo_KickPerson.Size(m)
}
func (m *KickPerson) XXX_DiscardUnknown() {
	xxx_messageInfo_KickPerson.DiscardUnknown(m)
}

var xxx_messageInfo_KickPerson proto.InternalMessageInfo

func (m *KickPerson) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// 更新在线状态
type UpdateOnline struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RegAddr              string   `protobuf:"bytes,2,opt,name=reg_addr,json=regAddr,proto3" json:"reg_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOnline) Reset()         { *m = UpdateOnline{} }
func (m *UpdateOnline) String() string { return proto.CompactTextString(m) }
func (*UpdateOnline) ProtoMessage()    {}
func (*UpdateOnline) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_service_c4098f6385432eb9, []int{25}
}
func (m *UpdateOnline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOnline.Unmarshal(m, b)
}
func (m *UpdateOnline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOnline.Marshal(b, m, deterministic)
}
func (dst *UpdateOnline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOnline.Merge(dst, src)
}
func (m *UpdateOnline) XXX_Size() int {
	return xxx_messageInfo_UpdateOnline.Size(m)
}
func (m *UpdateOnline) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOnline.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOnline proto.InternalMessageInfo

func (m *UpdateOnline) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateOnline) GetRegAddr() string {
	if m != nil {
		return m.RegAddr
	}
	return ""
}

func init() {
	proto.RegisterType((*BaseRequest)(nil), "BaseRequest")
	proto.RegisterType((*BaseResponse)(nil), "BaseResponse")
	proto.RegisterType((*RegisterStatusRequest)(nil), "RegisterStatusRequest")
	proto.RegisterType((*RegisterStatusResponse)(nil), "RegisterStatusResponse")
	proto.RegisterType((*QueryStatusRequest)(nil), "QueryStatusRequest")
	proto.RegisterType((*QueryStatusResponse)(nil), "QueryStatusResponse")
	proto.RegisterType((*CreateChatRoomReq)(nil), "CreateChatRoomReq")
	proto.RegisterType((*CreateChatRoomRsp)(nil), "CreateChatRoomRsp")
	proto.RegisterType((*UpdateOfflineReq)(nil), "UpdateOfflineReq")
	proto.RegisterType((*UpdateOfflineRsp)(nil), "UpdateOfflineRsp")
	proto.RegisterType((*DelChatRoomReq)(nil), "DelChatRoomReq")
	proto.RegisterType((*DelChatRoomRsp)(nil), "DelChatRoomRsp")
	proto.RegisterType((*ForceTerminateNotify)(nil), "ForceTerminateNotify")
	proto.RegisterType((*SingleAnswerSigToSig)(nil), "SingleAnswerSigToSig")
	proto.RegisterType((*GetChatRoomReq)(nil), "GetChatRoomReq")
	proto.RegisterType((*GetChatRoomRsp)(nil), "GetChatRoomRsp")
	proto.RegisterType((*SingleRefuseSigToSig)(nil), "SingleRefuseSigToSig")
	proto.RegisterType((*HangUpSigToSig)(nil), "HangUpSigToSig")
	proto.RegisterType((*SingleTerminal)(nil), "SingleTerminal")
	proto.RegisterType((*OfferCall)(nil), "OfferCall")
	proto.RegisterType((*OfferAnswer)(nil), "OfferAnswer")
	proto.RegisterType((*IceCall)(nil), "IceCall")
	proto.RegisterType((*IceAnswer)(nil), "IceAnswer")
	proto.RegisterType((*MediaToAudio)(nil), "MediaToAudio")
	proto.RegisterType((*KickPerson)(nil), "KickPerson")
	proto.RegisterType((*UpdateOnline)(nil), "UpdateOnline")
	proto.RegisterEnum("CMD", CMD_name, CMD_value)
	proto.RegisterEnum("ReturnCode", ReturnCode_name, ReturnCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StatusServerClient is the client API for StatusServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatusServerClient interface {
	BaseInterface(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error)
}

type statusServerClient struct {
	cc *grpc.ClientConn
}

func NewStatusServerClient(cc *grpc.ClientConn) StatusServerClient {
	return &statusServerClient{cc}
}

func (c *statusServerClient) BaseInterface(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, "/StatusServer/BaseInterface", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatusServerServer is the server API for StatusServer service.
type StatusServerServer interface {
	BaseInterface(context.Context, *BaseRequest) (*BaseResponse, error)
}

func RegisterStatusServerServer(s *grpc.Server, srv StatusServerServer) {
	s.RegisterService(&_StatusServer_serviceDesc, srv)
}

func _StatusServer_BaseInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusServerServer).BaseInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StatusServer/BaseInterface",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusServerServer).BaseInterface(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StatusServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "StatusServer",
	HandlerType: (*StatusServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BaseInterface",
			Handler:    _StatusServer_BaseInterface_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "status-service.proto",
}

func init() {
	proto.RegisterFile("status-service.proto", fileDescriptor_status_service_c4098f6385432eb9)
}

var fileDescriptor_status_service_c4098f6385432eb9 = []byte{
	// 1245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0x4d, 0x6f, 0xdb, 0x46,
	0x10, 0x0d, 0x25, 0xd9, 0x92, 0x46, 0x1f, 0xa1, 0xd7, 0x4a, 0xa2, 0x7c, 0x14, 0x51, 0x99, 0x16,
	0x30, 0x02, 0x54, 0x29, 0xdc, 0x63, 0x81, 0x02, 0x34, 0x45, 0x39, 0x84, 0x25, 0x31, 0x59, 0x4a,
	0x08, 0x92, 0x0b, 0x41, 0x71, 0x87, 0x32, 0x51, 0x9a, 0x54, 0x96, 0x94, 0x0b, 0xa1, 0xa7, 0x5e,
	0x8b, 0x5e, 0x7b, 0xee, 0x2f, 0xe8, 0x0f, 0x29, 0xd0, 0x1f, 0x55, 0x2c, 0x49, 0x59, 0x92, 0x9d,
	0xc6, 0xf6, 0xc1, 0x45, 0x4f, 0xe2, 0xbe, 0xd9, 0x99, 0xf7, 0xe6, 0xed, 0x88, 0x1f, 0xd0, 0x8a,
	0x13, 0x27, 0x59, 0xc4, 0xdf, 0xc4, 0xc8, 0xcf, 0x7d, 0x17, 0xbb, 0x73, 0x1e, 0x25, 0xd1, 0x93,
	0xc7, 0xb3, 0x28, 0x9a, 0x05, 0xf8, 0x2a, 0x5d, 0x4d, 0x17, 0xde, 0x2b, 0x27, 0x5c, 0x66, 0x21,
	0xc5, 0x87, 0xda, 0x91, 0x13, 0x23, 0xc5, 0x8f, 0x0b, 0x8c, 0x13, 0xf2, 0x0c, 0xaa, 0x3c, 0xbb,
	0x34, 0x58, 0x5b, 0xea, 0x48, 0x07, 0x55, 0xba, 0x06, 0x08, 0x01, 0xc9, 0x6d, 0x17, 0x3a, 0xd2,
	0x41, 0xf3, 0xb0, 0xd4, 0xd5, 0x86, 0x3d, 0x2a, 0xb9, 0xe4, 0x00, 0x4a, 0xd3, 0x88, 0x2d, 0xdb,
	0xc5, 0x8e, 0x74, 0x50, 0x3b, 0x6c, 0x75, 0x33, 0xaa, 0xee, 0x8a, 0xaa, 0xab, 0x86, 0x4b, 0x9a,
	0xee, 0x50, 0xfe, 0x90, 0xa0, 0x9e, 0x71, 0xc5, 0xf3, 0x28, 0x8c, 0xf1, 0x1a, 0xb2, 0xe7, 0x50,
	0x72, 0x23, 0x86, 0x39, 0x5f, 0xad, 0x4b, 0x31, 0x59, 0xf0, 0x50, 0x8b, 0x18, 0xd2, 0x34, 0x40,
	0x08, 0x94, 0x18, 0xc6, 0x6e, 0xca, 0x5c, 0xa5, 0xe9, 0x75, 0xa6, 0xb0, 0xf4, 0x69, 0x85, 0x3b,
	0xd7, 0x2a, 0xfc, 0x4b, 0x82, 0x07, 0x14, 0x67, 0x7e, 0x9c, 0x20, 0xb7, 0x52, 0x23, 0x57, 0xbe,
	0x3c, 0x81, 0x8a, 0xcf, 0x30, 0x4c, 0xfc, 0x64, 0x99, 0x2b, 0xbd, 0x58, 0x93, 0xa7, 0x50, 0xe5,
	0x51, 0x74, 0x66, 0x07, 0x7e, 0x9c, 0xb4, 0x0b, 0x9d, 0xa2, 0x08, 0x0a, 0x60, 0xe0, 0xc7, 0x09,
	0x69, 0xc1, 0xce, 0xfc, 0x34, 0x0a, 0x31, 0x57, 0x99, 0x2d, 0x44, 0xca, 0x22, 0x46, 0x6e, 0x87,
	0xce, 0x19, 0xa6, 0x72, 0xab, 0xb4, 0x22, 0x80, 0x91, 0x73, 0x86, 0xe4, 0x39, 0xd4, 0xd2, 0xa0,
	0x73, 0xee, 0x24, 0x11, 0x4f, 0x65, 0x57, 0x29, 0x08, 0x48, 0x4d, 0x11, 0xf2, 0x02, 0x1a, 0x3c,
	0x57, 0x69, 0xfb, 0xa1, 0x17, 0xb5, 0x77, 0xd3, 0x2d, 0xf5, 0x15, 0x68, 0x84, 0x5e, 0xa4, 0xb4,
	0xe1, 0xe1, 0xe5, 0x56, 0x32, 0xdb, 0x95, 0x6f, 0x81, 0xbc, 0x5d, 0x20, 0x5f, 0xde, 0xb8, 0x43,
	0xe5, 0xcf, 0x02, 0xec, 0x6f, 0xa5, 0xe4, 0x07, 0xf8, 0xbf, 0x72, 0xa5, 0x05, 0x3b, 0x62, 0xf8,
	0x31, 0x75, 0x63, 0x87, 0x66, 0x0b, 0xd2, 0x81, 0xba, 0x7b, 0xea, 0x24, 0x76, 0xaa, 0xc5, 0x67,
	0xed, 0x72, 0x96, 0x27, 0x30, 0x1a, 0x45, 0x67, 0x06, 0x13, 0xac, 0x81, 0x13, 0x27, 0xb6, 0x80,
	0xda, 0x95, 0x8e, 0x74, 0x50, 0xa4, 0x15, 0x01, 0x68, 0xa7, 0x4e, 0x42, 0x1e, 0x43, 0x85, 0xe3,
	0xcc, 0x76, 0x18, 0xe3, 0xed, 0x6a, 0x9a, 0x5a, 0xe6, 0x38, 0x53, 0x19, 0xe3, 0x22, 0x14, 0x79,
	0x9e, 0x1d, 0xf8, 0x21, 0xb6, 0xa1, 0x23, 0x1d, 0x54, 0x68, 0x39, 0xf2, 0xbc, 0x81, 0x1f, 0xa2,
	0xa2, 0xc1, 0x9e, 0xc6, 0xd1, 0x49, 0x50, 0xcb, 0x69, 0x28, 0x7e, 0x24, 0x0f, 0x61, 0xd7, 0x75,
	0x82, 0x00, 0x79, 0x6e, 0x55, 0xbe, 0x12, 0xb8, 0x13, 0xc6, 0x3f, 0x21, 0x4f, 0x27, 0xbd, 0x4a,
	0xf3, 0x95, 0x82, 0x57, 0x8a, 0xc4, 0xf3, 0xdb, 0x16, 0xb9, 0xd2, 0x7e, 0xf1, 0x72, 0xfb, 0x4a,
	0x17, 0xe4, 0xc9, 0x9c, 0x39, 0x09, 0x9a, 0x9e, 0x27, 0x7a, 0x11, 0x52, 0x3f, 0x37, 0x0b, 0xe4,
	0xf2, 0xfe, 0x78, 0xae, 0x1c, 0x42, 0xb3, 0x87, 0xc1, 0x66, 0xb3, 0x97, 0x79, 0xa5, 0x2b, 0xbc,
	0xf2, 0x76, 0x4e, 0x3c, 0x57, 0x2c, 0x68, 0xf5, 0x23, 0xee, 0xe2, 0x18, 0xf9, 0x99, 0x1f, 0x3a,
	0x09, 0x8e, 0xa2, 0xc4, 0xf7, 0x96, 0xd7, 0xd7, 0x4a, 0x8f, 0x22, 0x39, 0x15, 0xff, 0x06, 0x96,
	0xf7, 0x5f, 0x4e, 0xd7, 0x06, 0x53, 0x7e, 0x97, 0xa0, 0x65, 0xf9, 0xe1, 0x2c, 0x40, 0x35, 0x75,
	0xc4, 0xf2, 0x67, 0xe3, 0xc8, 0xf2, 0x67, 0x37, 0xa8, 0xfa, 0x25, 0xd4, 0x19, 0x8a, 0xbb, 0xa8,
	0x7d, 0x16, 0x31, 0x0c, 0xf2, 0xca, 0xb5, 0x0c, 0x1b, 0x0a, 0x48, 0xcc, 0x4e, 0x76, 0x00, 0x6b,
	0x6f, 0x2b, 0x19, 0x90, 0x0d, 0x56, 0x76, 0x0a, 0x22, 0x98, 0x8f, 0x73, 0x06, 0x18, 0x4c, 0x58,
	0x76, 0x8c, 0xc9, 0xed, 0x2c, 0x9b, 0x6e, 0xe7, 0xdc, 0xc9, 0x38, 0xf0, 0x95, 0x5d, 0x14, 0xbd,
	0x45, 0x8c, 0xb7, 0xb0, 0x6b, 0xcb, 0x8b, 0xc2, 0xe7, 0xbc, 0x28, 0x5e, 0xf2, 0xc2, 0x84, 0xe6,
	0x6b, 0x27, 0x9c, 0x4d, 0xe6, 0xb7, 0x63, 0x5b, 0x17, 0x2c, 0x5c, 0x2a, 0xb8, 0x80, 0x66, 0xd6,
	0x44, 0x3e, 0x4a, 0xc1, 0x4d, 0xe5, 0x87, 0x2e, 0x06, 0x5b, 0xf2, 0x05, 0x60, 0x30, 0xf2, 0x15,
	0x34, 0xa7, 0x68, 0x67, 0x4b, 0x64, 0xeb, 0x1e, 0xea, 0x53, 0xd4, 0x72, 0xd0, 0x60, 0xca, 0x12,
	0xaa, 0xa6, 0xe7, 0x21, 0xd7, 0x9c, 0x20, 0xb8, 0x4b, 0xc3, 0x88, 0x0c, 0xc5, 0x98, 0xcd, 0xf3,
	0x99, 0x12, 0x97, 0xca, 0xcf, 0x50, 0x4b, 0xa9, 0xd5, 0x4f, 0x9f, 0xf3, 0xdd, 0x92, 0xff, 0x2a,
	0x41, 0xd9, 0x70, 0xf1, 0xce, 0xdb, 0x7e, 0x01, 0x0d, 0xf1, 0x6f, 0x74, 0x9d, 0x90, 0xf9, 0xe2,
	0x0e, 0x94, 0x6b, 0xa8, 0xfb, 0x82, 0x3b, 0xc7, 0x94, 0xdf, 0x24, 0xa8, 0x1a, 0x2e, 0xfe, 0x07,
	0x46, 0xdc, 0x48, 0x4e, 0x0c, 0xf5, 0x21, 0x32, 0xdf, 0x19, 0x47, 0xea, 0x82, 0xf9, 0xd1, 0x0d,
	0x04, 0x7d, 0x01, 0xe0, 0x46, 0xe1, 0x39, 0xf2, 0x64, 0xad, 0xa8, 0x9a, 0x23, 0x06, 0x23, 0x0a,
	0x34, 0xc4, 0x28, 0xae, 0x77, 0x64, 0xb2, 0x6a, 0x53, 0xd4, 0x56, 0x7b, 0x94, 0xaf, 0x01, 0x4e,
	0x7c, 0xf7, 0xc7, 0x37, 0xc8, 0xe3, 0x28, 0x24, 0x8f, 0xa0, 0x9c, 0x3e, 0x39, 0x2f, 0xd8, 0x76,
	0xc5, 0xd2, 0x60, 0xca, 0x11, 0xd4, 0xf3, 0x5b, 0x79, 0x28, 0xee, 0xe4, 0xff, 0xba, 0x71, 0xeb,
	0x29, 0x58, 0xd8, 0x7a, 0x0a, 0xbe, 0xfc, 0xbb, 0x08, 0x45, 0x6d, 0xd8, 0x23, 0xfb, 0x70, 0x9f,
	0xea, 0xc7, 0x86, 0x35, 0xd6, 0xa9, 0x6d, 0x8d, 0xd5, 0xf1, 0xc4, 0x92, 0xef, 0x11, 0x19, 0xea,
	0x6f, 0x27, 0x3a, 0x7d, 0xbf, 0x42, 0x24, 0xd2, 0x02, 0x59, 0xa3, 0xba, 0x3a, 0xd6, 0x6d, 0xed,
	0xb5, 0x3a, 0xb6, 0xa9, 0x69, 0x0e, 0xe5, 0x82, 0x48, 0x9e, 0xbc, 0xe9, 0x09, 0xd4, 0xec, 0xf7,
	0xed, 0x81, 0x31, 0xd2, 0xe5, 0x22, 0xd9, 0x83, 0x46, 0x4f, 0x1f, 0x6c, 0xec, 0x2b, 0x91, 0x87,
	0x40, 0x2c, 0x63, 0x74, 0x3c, 0xd0, 0x6d, 0x4d, 0x1d, 0x0c, 0xec, 0x91, 0x39, 0x36, 0xfa, 0xef,
	0xe5, 0x1d, 0xf2, 0x18, 0x1e, 0xf4, 0x4d, 0xaa, 0xe9, 0xf6, 0x58, 0xa7, 0x43, 0x63, 0xa4, 0x5e,
	0x84, 0x76, 0xc9, 0x33, 0x68, 0xe7, 0x29, 0xea, 0xc8, 0x7a, 0x27, 0xc4, 0x19, 0xc7, 0xf6, 0xd8,
	0x14, 0x3f, 0x72, 0x99, 0x3c, 0x80, 0xbd, 0x63, 0x7d, 0xbc, 0xe6, 0xb0, 0xa9, 0xfe, 0x56, 0xae,
	0x6c, 0x24, 0x51, 0xbd, 0x3f, 0xb1, 0xf4, 0xcd, 0xa4, 0xaa, 0x50, 0xf1, 0x5a, 0x1d, 0x1d, 0xdb,
	0x93, 0x37, 0x9b, 0x38, 0x90, 0x47, 0xb0, 0x7f, 0xc1, 0xbf, 0x11, 0xa8, 0x09, 0x79, 0x66, 0xbf,
	0xaf, 0xd3, 0x4c, 0xf5, 0x46, 0xa8, 0x4e, 0x9e, 0xc2, 0xa3, 0x2c, 0x74, 0x55, 0x5d, 0x43, 0x14,
	0x34, 0x34, 0xfd, 0x4a, 0x56, 0x53, 0x14, 0x14, 0x81, 0xab, 0x39, 0xf7, 0x85, 0x38, 0x6d, 0xd8,
	0xb3, 0x87, 0x7a, 0xcf, 0x50, 0x05, 0xaa, 0x4e, 0x7a, 0x86, 0x29, 0xcb, 0xc2, 0x4d, 0x81, 0x9f,
	0x18, 0xda, 0x89, 0x3d, 0xb1, 0x74, 0x2a, 0xef, 0x11, 0x02, 0xcd, 0x95, 0xeb, 0xa3, 0xcc, 0x74,
	0xf2, 0xf2, 0x17, 0x09, 0x60, 0xfd, 0xa2, 0x4d, 0x6a, 0x50, 0xb6, 0x26, 0x9a, 0xa6, 0x5b, 0xe2,
	0x34, 0x9b, 0x00, 0x93, 0xd1, 0x89, 0xf9, 0x6e, 0x64, 0x6b, 0xc3, 0x9e, 0x2c, 0x89, 0xd3, 0x3d,
	0x32, 0x7b, 0xef, 0x6d, 0xc3, 0xb2, 0x47, 0x93, 0xc1, 0x40, 0x2e, 0x08, 0x5d, 0x3d, 0xdd, 0xd2,
	0xa9, 0xa1, 0x0e, 0x8c, 0x0f, 0xea, 0xd8, 0x30, 0x47, 0xb6, 0x4e, 0xa9, 0x49, 0xe5, 0xa2, 0xe8,
	0xe5, 0x53, 0x81, 0x92, 0xa8, 0x92, 0x57, 0xcd, 0x90, 0x9d, 0xc3, 0x1f, 0xa0, 0x9e, 0xbd, 0x67,
	0x5a, 0xc8, 0xcf, 0x91, 0x93, 0x2e, 0x34, 0xc4, 0x67, 0x83, 0x11, 0x26, 0xc8, 0x3d, 0xc7, 0x45,
	0x52, 0xef, 0x6e, 0x7c, 0xb2, 0x3c, 0x69, 0x74, 0x37, 0x3f, 0x2a, 0x94, 0x7b, 0x47, 0xfb, 0x1f,
	0xf6, 0xba, 0xdf, 0xaf, 0xde, 0xee, 0x3d, 0xe4, 0x36, 0x43, 0x6f, 0xba, 0x9b, 0x02, 0xdf, 0xfd,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x91, 0xb4, 0x50, 0x60, 0x21, 0x0d, 0x00, 0x00,
}
